name: g6-backend

spec:
  name: g6-backend
  region: nyc
  
  services:
    - name: api
      # DigitalOcean detectar치 autom치ticamente que es PHP/Laravel
      environment_slug: php
      
      # Comandos de construcci칩n
      build_command: |
        composer install --no-dev --optimize-autoloader
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
      
      # Comando para ejecutar la aplicaci칩n
      run_command: |
        heroku-php-apache2 public/
      
      # Puerto HTTP
      http_port: 8080
      
      # Plan (esto es $12/mes - Basic)
      instance_size_slug: basic-xxs
      instance_count: 1
      
      # Variables de entorno
      envs:
        - key: APP_NAME
          value: "G6"
        
        - key: APP_ENV
          value: "production"
        
        - key: APP_DEBUG
          value: "false"
        
        - key: APP_URL
          scope: RUN_TIME
          value: "${APP_URL}"
        
        - key: APP_KEY
          scope: RUN_TIME
          type: SECRET
        
        - key: DB_CONNECTION
          value: "mysql"
        
        - key: DB_HOST
          scope: RUN_TIME
          value: "${db.HOSTNAME}"
        
        - key: DB_PORT
          scope: RUN_TIME
          value: "${db.PORT}"
        
        - key: DB_DATABASE
          scope: RUN_TIME
          value: "${db.DATABASE}"
        
        - key: DB_USERNAME
          scope: RUN_TIME
          value: "${db.USERNAME}"
        
        - key: DB_PASSWORD
          scope: RUN_TIME
          type: SECRET
          value: "${db.PASSWORD}"
  
  databases:
    - name: db
      engine: MYSQL
      production: false